homeassistant:
  name: Mobile Alerts Test
  unit_system: metric
  time_zone: UTC

logger:
  default: info
  logs:
    custom_components.mobile_alerts: debug

# Enable HTTP API
http:

# Enable WebSocket API
websocket_api:

# History
history:
  exclude:
    entities: []

# API Password (deprecated but needed for legacy access)
api:

# Minimal configuration
mobile_alerts:
  phone_id: "405930384241"
  devices:
    - device_id: "090005AC99E2"
      name: "Example Hanover T1"
      type: "t1"
    - device_id: "090005AC99E2"
      name: "Example Hanover T2"
      type: "t2"
    - device_id: "0301548CBC4A"
      name: "Example Berlin T1"
      type: "t1"
